(MainThread) 170224_13:48:44.321 DEBUG IB_stop_loss.py:1491 Using args Namespace(global_cancel=False, port=7497)
(MainThread) 170224_13:48:44.327 DEBUG client.py:71 140067794068816 connState: None -> 0
(MainThread) 170224_13:48:44.331 DEBUG client.py:131 Connecting to 127.0.0.1:7497 w/ id:0
(MainThread) 170224_13:48:44.332 DEBUG client.py:71 140067794068816 connState: 0 -> 1
(MainThread) 170224_13:48:44.332 DEBUG client.py:144 msg b'\x00\x00\x00\tv100..109'
(MainThread) 170224_13:48:44.332 DEBUG client.py:146 REQUEST b'API\x00\x00\x00\x00\tv100..109'
(MainThread) 170224_13:48:44.333 DEBUG connection.py:71 acquiring lock
(MainThread) 170224_13:48:44.333 DEBUG connection.py:73 acquired lock
(MainThread) 170224_13:48:44.333 DEBUG connection.py:80 releasing lock
(MainThread) 170224_13:48:44.333 DEBUG connection.py:82 release lock
(MainThread) 170224_13:48:44.333 DEBUG connection.py:84 sendMsg: sent: 17
(MainThread) 170224_13:48:44.337 DEBUG decoder.py:977 no fields
(MainThread) 170224_13:48:44.337 DEBUG connection.py:90 acquiring lock
(MainThread) 170224_13:48:44.337 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:48:44.338 DEBUG connection.py:115 len 30 raw:b'\x00\x00\x00\x1a109\x0020170224 13:48:44 CAT\x00'|
(MainThread) 170224_13:48:44.338 DEBUG connection.py:101 releasing lock
(MainThread) 170224_13:48:44.338 DEBUG connection.py:103 release lock
(MainThread) 170224_13:48:44.338 DEBUG client.py:156 ANSWER b'\x00\x00\x00\x1a109\x0020170224 13:48:44 CAT\x00'
(MainThread) 170224_13:48:44.338 DEBUG comm.py:53 read_msg: size: 26
(MainThread) 170224_13:48:44.338 DEBUG client.py:159 size:26 msg:b'109\x0020170224 13:48:44 CAT\x00' rest:b''|
(MainThread) 170224_13:48:44.338 DEBUG client.py:161 fields (b'109', b'20170224 13:48:44 CAT')
(MainThread) 170224_13:48:44.338 DEBUG client.py:167 ANSWER Version:109 time:b'20170224 13:48:44 CAT'
(MainThread) 170224_13:48:44.338 DEBUG client.py:71 140067794068816 connState: 1 -> 2
(Thread-2) 170224_13:48:44.339 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:48:44.339 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:48:44.339 INFO client.py:176 sent startApi
(MainThread) 170224_13:48:44.339 INFO client.py:86 REQUEST startApi {}
(MainThread) 170224_13:48:44.339 DEBUG client.py:203 140067794068816 isConn: 2
(MainThread) 170224_13:48:44.339 INFO client.py:75 SENDING countReqId_ b'\x00\x00\x00\x0871\x002\x000\x00\x00'
(MainThread) 170224_13:48:44.340 DEBUG connection.py:71 acquiring lock
(Thread-2) 170224_13:48:45.340 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32108>)
(Thread-2) 170224_13:48:45.341 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:48:45.342 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:48:45.342 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:48:45.343 DEBUG connection.py:90 acquiring lock
(MainThread) 170224_13:48:45.344 DEBUG connection.py:73 acquired lock
(MainThread) 170224_13:48:45.345 DEBUG connection.py:80 releasing lock
(MainThread) 170224_13:48:45.345 DEBUG connection.py:82 release lock
(MainThread) 170224_13:48:45.346 DEBUG connection.py:84 sendMsg: sent: 12
(Thread-2) 170224_13:48:45.347 DEBUG connection.py:92 acquired lock
(Thread-2) 170224_13:48:45.369 DEBUG connection.py:115 len 17 raw:b'\x00\x00\x00\r15\x001\x00DU15047\x00'|
(Thread-2) 170224_13:48:45.369 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:48:45.370 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:48:45.370 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 17 buf b'\x00\x00\x00\r15\x001\x00DU15047\x00'
(Thread-2) 170224_13:48:45.370 DEBUG comm.py:53 read_msg: size: 13
(Thread-2) 170224_13:48:45.370 DEBUG reader.py:40 size:13 msg.size:13 msg:|b''| buf:||
(Thread-2) 170224_13:48:45.370 DEBUG connection.py:90 acquiring lock
(MainThread) 170224_13:48:45.370 DEBUG client.py:234 fields (b'15', b'1', b'DU15047')
(Thread-2) 170224_13:48:45.371 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:48:45.371 DEBUG decoder.py:958 field b'DU15047' 
(Thread-2) 170224_13:48:45.371 DEBUG connection.py:115 len 125 raw:b'\x00\x00\x00\x079\x001\x0051\x00\x00\x00\x0054\x002\x00-1\x002104\x00Market data farm connection is OK:ibdemo\x00\x00\x00\x0054\x002\x00-1\x002106\x00HMDS data farm connection is OK:demohmds\x00'|
(MainThread) 170224_13:48:45.371 DEBUG decoder.py:960 arg DU15047 type <class 'str'>
(Thread-2) 170224_13:48:45.372 DEBUG connection.py:101 releasing lock
(MainThread) 170224_13:48:45.372 DEBUG decoder.py:971 calling <function TestApp.managedAccounts at 0x7f63f6d0a8c8> with <__main__.TestApp object at 0x7f64131c2550> ['DU15047']
(Thread-2) 170224_13:48:45.372 DEBUG connection.py:103 release lock
(MainThread) 170224_13:48:45.372 INFO wrapper.py:41 ANSWER managedAccounts {'accountsList': 'DU15047'}
(Thread-2) 170224_13:48:45.372 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 125 buf b'\x00\x00\x00\x079\x001\x0051\x00\x00\x00\x0054\x002\x00-1\x002104\x00Market data farm connection is OK:ibdemo\x00\x00\x00\x0054\x002\x00-1\x002106\x00HMDS data farm connection is OK:demohmds\x00'
(MainThread) 170224_13:48:45.373 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:48:45.373 DEBUG comm.py:53 read_msg: size: 7
(Thread-2) 170224_13:48:45.373 DEBUG reader.py:40 size:7 msg.size:7 msg:|b'\x00\x00\x0054\x002\x00-1\x002104\x00Market data farm connection is OK:ibdemo\x00\x00\x00\x0054\x002\x00-1\x002106\x00HMDS data farm connection is OK:demohmds\x00'| buf:||
(Thread-2) 170224_13:48:45.373 DEBUG comm.py:53 read_msg: size: 53
(MainThread) 170224_13:48:45.374 DEBUG client.py:234 fields (b'9', b'1', b'51')
(Thread-2) 170224_13:48:45.374 DEBUG reader.py:40 size:53 msg.size:53 msg:|b'\x00\x00\x0054\x002\x00-1\x002106\x00HMDS data farm connection is OK:demohmds\x00'| buf:||
(MainThread) 170224_13:48:45.374 DEBUG decoder.py:958 field b'51' 
(Thread-2) 170224_13:48:45.374 DEBUG comm.py:53 read_msg: size: 53
(MainThread) 170224_13:48:45.374 DEBUG decoder.py:960 arg 51 type <class 'int'>
(Thread-2) 170224_13:48:45.375 DEBUG reader.py:40 size:53 msg.size:53 msg:|b''| buf:||
(MainThread) 170224_13:48:45.375 DEBUG decoder.py:971 calling <function TestApp.nextValidId at 0x7f63f6d0a158> with <__main__.TestApp object at 0x7f64131c2550> [51]
(Thread-2) 170224_13:48:45.375 DEBUG connection.py:90 acquiring lock
(MainThread) 170224_13:48:45.375 INFO wrapper.py:41 ANSWER nextValidId {'orderId': 51}
(Thread-2) 170224_13:48:45.375 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:48:45.376 DEBUG IB_stop_loss.py:238 setting nextValidOrderId: 51
(MainThread) 170224_13:48:45.376 INFO client.py:86 REQUEST reqMarketDataType {'marketDataType': 3}
(MainThread) 170224_13:48:45.376 DEBUG client.py:203 140067794068816 isConn: 2
(MainThread) 170224_13:48:45.376 INFO client.py:75 SENDING countReqId_ b'\x00\x00\x00\x0759\x001\x003\x00'
(MainThread) 170224_13:48:45.376 DEBUG connection.py:71 acquiring lock
(Thread-2) 170224_13:48:46.376 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32188>)
(Thread-2) 170224_13:48:46.377 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:48:46.377 DEBUG connection.py:103 release lock
(MainThread) 170224_13:48:46.377 DEBUG connection.py:73 acquired lock
(Thread-2) 170224_13:48:46.377 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(MainThread) 170224_13:48:46.378 DEBUG connection.py:80 releasing lock
(Thread-2) 170224_13:48:46.378 DEBUG connection.py:90 acquiring lock
(MainThread) 170224_13:48:46.379 DEBUG connection.py:82 release lock
(Thread-2) 170224_13:48:46.379 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:48:46.379 DEBUG connection.py:84 sendMsg: sent: 11
(MainThread) 170224_13:48:46.379 DEBUG client.py:246 conn:1 queue.sz:2
(MainThread) 170224_13:48:46.380 DEBUG client.py:234 fields (b'4', b'2', b'-1', b'2104', b'Market data farm connection is OK:ibdemo')
(MainThread) 170224_13:48:46.380 DEBUG decoder.py:958 field b'-1' 
(MainThread) 170224_13:48:46.380 DEBUG decoder.py:960 arg -1 type <class 'int'>
(MainThread) 170224_13:48:46.380 DEBUG decoder.py:958 field b'2104' 
(MainThread) 170224_13:48:46.380 DEBUG decoder.py:960 arg 2104 type <class 'int'>
(MainThread) 170224_13:48:46.380 DEBUG decoder.py:958 field b'Market data farm connection is OK:ibdemo' 
(MainThread) 170224_13:48:46.381 DEBUG decoder.py:960 arg Market data farm connection is OK:ibdemo type <class 'str'>
(MainThread) 170224_13:48:46.381 DEBUG decoder.py:971 calling <function TestApp.error at 0x7f63f6d0a400> with <__main__.TestApp object at 0x7f64131c2550> [-1, 2104, 'Market data farm connection is OK:ibdemo']
(MainThread) 170224_13:48:46.381 INFO wrapper.py:41 ANSWER error {'reqId': -1, 'errorString': 'Market data farm connection is OK:ibdemo', 'errorCode': 2104}
(MainThread) 170224_13:48:46.381 ERROR wrapper.py:49 ERROR -1 2104 Market data farm connection is OK:ibdemo
(MainThread) 170224_13:48:46.381 DEBUG client.py:246 conn:1 queue.sz:1
(MainThread) 170224_13:48:46.382 DEBUG client.py:234 fields (b'4', b'2', b'-1', b'2106', b'HMDS data farm connection is OK:demohmds')
(MainThread) 170224_13:48:46.382 DEBUG decoder.py:958 field b'-1' 
(MainThread) 170224_13:48:46.382 DEBUG decoder.py:960 arg -1 type <class 'int'>
(MainThread) 170224_13:48:46.382 DEBUG decoder.py:958 field b'2106' 
(MainThread) 170224_13:48:46.382 DEBUG decoder.py:960 arg 2106 type <class 'int'>
(MainThread) 170224_13:48:46.382 DEBUG decoder.py:958 field b'HMDS data farm connection is OK:demohmds' 
(MainThread) 170224_13:48:46.383 DEBUG decoder.py:960 arg HMDS data farm connection is OK:demohmds type <class 'str'>
(MainThread) 170224_13:48:46.383 DEBUG decoder.py:971 calling <function TestApp.error at 0x7f63f6d0a400> with <__main__.TestApp object at 0x7f64131c2550> [-1, 2106, 'HMDS data farm connection is OK:demohmds']
(MainThread) 170224_13:48:46.383 INFO wrapper.py:41 ANSWER error {'reqId': -1, 'errorString': 'HMDS data farm connection is OK:demohmds', 'errorCode': 2106}
(MainThread) 170224_13:48:46.383 ERROR wrapper.py:49 ERROR -1 2106 HMDS data farm connection is OK:demohmds
(MainThread) 170224_13:48:46.383 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:46.584 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:46.584 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:46.785 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:46.785 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:46.985 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:46.986 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:47.187 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:47.187 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:48:47.380 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d322c8>)
(Thread-2) 170224_13:48:47.381 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:48:47.381 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:48:47.381 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:48:47.381 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:48:47.381 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:48:47.388 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:47.388 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:47.589 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:47.589 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:47.790 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:47.790 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:47.991 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:47.991 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:48.191 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:48.191 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:48:48.382 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d323c8>)
(Thread-2) 170224_13:48:48.383 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:48:48.383 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:48:48.383 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:48:48.383 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:48:48.383 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:48:48.392 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:48.392 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:48.592 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:48.592 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:48.793 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:48.793 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:48.993 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:48.994 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:49.194 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:49.194 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:48:49.384 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32388>)
(Thread-2) 170224_13:48:49.385 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:48:49.385 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:48:49.385 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:48:49.385 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:48:49.385 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:48:49.394 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:49.394 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:49.595 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:49.595 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:49.795 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:49.796 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:49.996 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:49.996 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:50.197 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:50.197 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:48:50.386 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32308>)
(Thread-2) 170224_13:48:50.386 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:48:50.387 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:48:50.387 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:48:50.387 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:48:50.387 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:48:50.397 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:50.397 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:50.598 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:50.598 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:50.798 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:50.798 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:50.999 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:50.999 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:51.199 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:51.199 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:48:51.388 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32148>)
(Thread-2) 170224_13:48:51.388 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:48:51.388 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:48:51.388 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:48:51.388 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:48:51.388 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:48:51.400 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:51.400 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:51.600 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:51.604 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:51.805 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:51.805 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:52.006 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:52.006 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:52.207 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:52.208 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:48:52.390 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32248>)
(Thread-2) 170224_13:48:52.390 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:48:52.390 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:48:52.390 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:48:52.390 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:48:52.390 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:48:52.408 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:52.408 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:52.609 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:52.609 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:52.809 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:52.809 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:53.010 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:53.011 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:53.211 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:53.212 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:48:53.392 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32348>)
(Thread-2) 170224_13:48:53.392 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:48:53.392 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:48:53.392 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:48:53.392 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:48:53.392 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:48:53.413 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:53.413 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:53.614 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:53.614 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:53.815 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:53.815 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:54.016 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:54.017 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:54.217 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:54.218 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:48:54.394 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d322c8>)
(Thread-2) 170224_13:48:54.394 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:48:54.394 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:48:54.394 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:48:54.394 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:48:54.395 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:48:54.419 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:54.419 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:54.620 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:54.620 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:54.821 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:54.821 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:55.022 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:55.022 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:55.222 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:55.223 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:48:55.396 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d323c8>)
(Thread-2) 170224_13:48:55.397 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:48:55.397 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:48:55.397 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:48:55.397 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:48:55.398 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:48:55.423 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:55.424 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:55.624 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:55.624 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:55.825 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:55.825 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:56.026 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:56.026 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:56.227 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:56.227 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:48:56.398 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32388>)
(Thread-2) 170224_13:48:56.399 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:48:56.400 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:48:56.400 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:48:56.401 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:48:56.401 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:48:56.428 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:56.428 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:56.629 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:56.629 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:56.830 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:56.831 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:57.031 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:57.032 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:57.232 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:57.233 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:48:57.403 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32308>)
(Thread-2) 170224_13:48:57.404 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:48:57.404 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:48:57.405 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:48:57.405 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:48:57.406 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:48:57.433 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:57.433 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:57.634 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:57.634 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:57.834 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:57.835 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:58.035 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:58.035 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:58.236 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:58.236 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:48:58.408 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32148>)
(Thread-2) 170224_13:48:58.409 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:48:58.409 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:48:58.410 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:48:58.410 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:48:58.411 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:48:58.437 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:58.437 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:58.638 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:58.638 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:58.838 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:58.839 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:59.039 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:59.039 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:59.240 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:59.240 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:48:59.413 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32248>)
(Thread-2) 170224_13:48:59.413 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:48:59.414 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:48:59.414 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:48:59.414 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:48:59.415 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:48:59.441 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:59.442 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:59.642 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:59.642 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:48:59.843 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:48:59.844 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:00.045 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:00.045 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:00.246 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:00.247 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:49:00.416 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32348>)
(Thread-2) 170224_13:49:00.417 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:49:00.417 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:49:00.417 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:49:00.417 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:49:00.417 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:49:00.448 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:00.448 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:00.649 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:00.649 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:00.850 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:00.851 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:01.052 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:01.052 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:01.252 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:01.252 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:49:01.418 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d322c8>)
(Thread-2) 170224_13:49:01.419 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:49:01.419 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:49:01.419 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:49:01.419 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:49:01.419 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:49:01.453 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:01.453 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:01.653 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:01.654 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:01.854 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:01.855 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:02.061 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:02.062 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:02.262 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:02.263 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:49:02.421 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d323c8>)
(Thread-2) 170224_13:49:02.421 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:49:02.421 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:49:02.422 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:49:02.422 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:49:02.422 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:49:02.463 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:02.464 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:02.664 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:02.664 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:02.865 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:02.865 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:03.066 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:03.067 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:03.267 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:03.268 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:49:03.424 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32388>)
(Thread-2) 170224_13:49:03.424 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:49:03.425 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:49:03.425 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:49:03.425 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:49:03.426 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:49:03.469 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:03.469 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:03.670 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:03.671 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:03.872 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:03.873 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:04.073 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:04.074 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:04.274 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:04.274 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:49:04.427 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32308>)
(Thread-2) 170224_13:49:04.428 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:49:04.429 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:49:04.429 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:49:04.429 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:49:04.429 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:49:04.474 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:04.475 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:04.675 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:04.675 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:04.876 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:04.876 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:05.076 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:05.077 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:05.277 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:05.278 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:49:05.431 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32148>)
(Thread-2) 170224_13:49:05.432 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:49:05.432 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:49:05.432 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:49:05.432 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:49:05.433 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:49:05.478 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:05.478 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:05.679 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:05.679 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:05.879 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:05.880 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:06.081 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:06.081 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:06.282 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:06.282 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:49:06.434 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32248>)
(Thread-2) 170224_13:49:06.435 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:49:06.435 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:49:06.436 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:49:06.436 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:49:06.436 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:49:06.483 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:06.484 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:06.685 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:06.685 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:06.886 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:06.886 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:07.087 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:07.087 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:07.287 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:07.288 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:49:07.438 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32348>)
(Thread-2) 170224_13:49:07.439 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:49:07.439 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:49:07.439 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:49:07.440 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:49:07.440 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:49:07.488 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:07.489 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:07.689 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:07.689 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:07.890 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:07.891 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:08.091 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:08.092 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:08.292 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:08.293 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:49:08.441 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d322c8>)
(Thread-2) 170224_13:49:08.442 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:49:08.443 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:49:08.443 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:49:08.444 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:49:08.444 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:49:08.494 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:08.494 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:08.695 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:08.695 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:08.897 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:08.897 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:09.098 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:09.099 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:09.300 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:09.300 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:49:09.445 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d323c8>)
(Thread-2) 170224_13:49:09.446 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:49:09.446 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:49:09.446 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:49:09.446 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:49:09.446 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:49:09.501 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:09.501 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:09.702 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:09.702 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:09.902 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:09.903 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:10.103 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:10.103 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:10.304 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:10.304 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:49:10.447 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32388>)
(Thread-2) 170224_13:49:10.448 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:49:10.448 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:49:10.448 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:49:10.449 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:49:10.449 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:49:10.505 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:10.505 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:10.706 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:10.706 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:10.907 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:10.907 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:11.108 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:11.108 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:11.309 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:11.309 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:49:11.450 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32308>)
(Thread-2) 170224_13:49:11.450 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:49:11.451 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:49:11.451 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:49:11.451 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:49:11.451 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:49:11.510 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:11.510 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:11.711 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:11.711 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:11.912 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:11.913 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:12.114 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:12.114 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:12.314 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:12.315 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:49:12.452 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32148>)
(Thread-2) 170224_13:49:12.453 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:49:12.453 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:49:12.454 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:49:12.454 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:49:12.454 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:49:12.515 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:12.516 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:12.717 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:12.717 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:12.918 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:12.918 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:13.119 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:13.119 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:13.320 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:13.321 DEBUG client.py:246 conn:1 queue.sz:0
(Thread-2) 170224_13:49:13.456 DEBUG connection.py:96 exception from recvMsg (<class 'socket.timeout'>, timeout('timed out',), <traceback object at 0x7f63f6d32248>)
(Thread-2) 170224_13:49:13.456 DEBUG connection.py:101 releasing lock
(Thread-2) 170224_13:49:13.457 DEBUG connection.py:103 release lock
(Thread-2) 170224_13:49:13.457 DEBUG reader.py:34 reader loop, prevBuf.size: 0 recvd size: 0 buf b''
(Thread-2) 170224_13:49:13.457 DEBUG connection.py:90 acquiring lock
(Thread-2) 170224_13:49:13.458 DEBUG connection.py:92 acquired lock
(MainThread) 170224_13:49:13.521 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:13.522 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:13.723 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:13.723 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:13.924 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:13.924 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:14.125 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:14.125 DEBUG client.py:246 conn:1 queue.sz:0
(MainThread) 170224_13:49:14.326 DEBUG client.py:231 queue.get: empty
(MainThread) 170224_13:49:14.327 DEBUG client.py:246 conn:1 queue.sz:0
